### ISSUE TITLE
Arguments failing to parse

### ISSUE THREAD

**Issue by DAMO-IS-LOUD** [ep1cman/DnD-Card-Generator#1]
Having trouble making the code work for me. I am new to Python, but not to coding (though at a basic level).

I have set VSC up and have installed the required packages, but have not identified the error returned when the arguments are parsed towards the end of the code. At approx. line 770: args = parser.parse_args() keeps returning a SystemExit 2 error.

I am probably at a greater disadvantage because I sort of know what I am doing. I get that the code is trying to pull the inputs together to dump it into the final file, but the general Python tutorials I've found on parsing arguments seem too basic to be applied to your program. Given I'm likely to only use this one item, I don't feel a need to become an expert in the language.

By the way, I think the code is great. Even with my small level of experience, I can see what everything is doing; I just can't diagnose my problem on my own.

**Comment by ep1cman** [comment]
Hi,

I will gladly try to resolve the issue, could you copy in the whole error log that shows up when you try to run the program (including the command you ran), and can you confirm what operating system you are using?

**Comment by DAMO-IS-LOUD** [comment]
I was a typical male who didn't read the instructions. A mate who _did_ know what he was doing has shown me how to use the 'Usage' information! The only thing I hadn't understood was defining the input, and he's shown me how to do that now.

Thanks for getting back to me so quickly! I'm really pleased with the result of the code.

**Comment by ep1cman** [comment]
Glad you got it working, would love to see what you end up using it for! If you encounter any other issues or have feedback feel free to open other issues here on GitHub
